[package]
name = "adventofcode-2016-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.7"

[dev-dependencies]
rstest = "0.15.0"
criterion = "0.3.6"